// <auto-generated />
using System;
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Entities.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Entities.Barangay", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("LocalGovernmentUnitId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LocalGovernmentUnitId");

                    b.ToTable("Barangays");
                });

            modelBuilder.Entity("Entities.Country", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("Entities.Facility", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("BarangayId")
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FacilityStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FacilityTypeId")
                        .HasColumnType("text");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("PostalCode")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BarangayId");

                    b.HasIndex("FacilityTypeId");

                    b.ToTable("Facilities");
                });

            modelBuilder.Entity("Entities.FacilityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FacilityRoles");
                });

            modelBuilder.Entity("Entities.FacilityType", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FacilityTypes");
                });

            modelBuilder.Entity("Entities.FacilityUser", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FacilityRoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "FacilityId");

                    b.HasIndex("FacilityId");

                    b.HasIndex("FacilityRoleId");

                    b.ToTable("FacilityUsers");
                });

            modelBuilder.Entity("Entities.LocalGovernmentUnit", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("ProvinceId")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProvinceId");

                    b.ToTable("LocalGovernmentUnits");
                });

            modelBuilder.Entity("Entities.Province", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("RegionId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.ToTable("Provinces");
                });

            modelBuilder.Entity("Entities.Region", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CountryId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("HomeAddress")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("MiddleName")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Entities.Barangay", b =>
                {
                    b.HasOne("Entities.LocalGovernmentUnit", "LocalGovernmentUnit")
                        .WithMany("Barangays")
                        .HasForeignKey("LocalGovernmentUnitId");

                    b.Navigation("LocalGovernmentUnit");
                });

            modelBuilder.Entity("Entities.Facility", b =>
                {
                    b.HasOne("Entities.Barangay", "Barangay")
                        .WithMany("Facilities")
                        .HasForeignKey("BarangayId");

                    b.HasOne("Entities.FacilityType", "FacilityType")
                        .WithMany("Facilities")
                        .HasForeignKey("FacilityTypeId");

                    b.Navigation("Barangay");

                    b.Navigation("FacilityType");
                });

            modelBuilder.Entity("Entities.FacilityUser", b =>
                {
                    b.HasOne("Entities.Facility", "Facility")
                        .WithMany("FacilityUsers")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.FacilityRole", "FacilityRole")
                        .WithMany("FacilityUsers")
                        .HasForeignKey("FacilityRoleId");

                    b.HasOne("Entities.User", "User")
                        .WithMany("FacilityUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Facility");

                    b.Navigation("FacilityRole");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entities.LocalGovernmentUnit", b =>
                {
                    b.HasOne("Entities.Province", "Province")
                        .WithMany("LocalGovernmentUnits")
                        .HasForeignKey("ProvinceId");

                    b.Navigation("Province");
                });

            modelBuilder.Entity("Entities.Province", b =>
                {
                    b.HasOne("Entities.Region", "Region")
                        .WithMany("Provinces")
                        .HasForeignKey("RegionId");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("Entities.Region", b =>
                {
                    b.HasOne("Entities.Country", "Country")
                        .WithMany("Regions")
                        .HasForeignKey("CountryId");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Entities.Barangay", b =>
                {
                    b.Navigation("Facilities");
                });

            modelBuilder.Entity("Entities.Country", b =>
                {
                    b.Navigation("Regions");
                });

            modelBuilder.Entity("Entities.Facility", b =>
                {
                    b.Navigation("FacilityUsers");
                });

            modelBuilder.Entity("Entities.FacilityRole", b =>
                {
                    b.Navigation("FacilityUsers");
                });

            modelBuilder.Entity("Entities.FacilityType", b =>
                {
                    b.Navigation("Facilities");
                });

            modelBuilder.Entity("Entities.LocalGovernmentUnit", b =>
                {
                    b.Navigation("Barangays");
                });

            modelBuilder.Entity("Entities.Province", b =>
                {
                    b.Navigation("LocalGovernmentUnits");
                });

            modelBuilder.Entity("Entities.Region", b =>
                {
                    b.Navigation("Provinces");
                });

            modelBuilder.Entity("Entities.User", b =>
                {
                    b.Navigation("FacilityUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
